### ISSUE TITLE
(Failure: 500) and then (Failure: 403) on uploading a file with proper folder access

### ISSUE THREAD

**Issue by tahaimt** [Alfresco/acs-community-packaging#593]
I am using the latest version of all images, prior to this I have also tried the exact versions listed in the docker-compose file. I get the same error with both configs while trying to upload a file to any directory. I mostly get 403 with nothing in logs but when I get 500, this is what I find in logs. Someone [here](https://github.com/Alfresco/acs-community-packaging/issues/227) suggested to change change the version to a specific version but if it had been fixed, it should also be fixed in the latest version.

```
share_1                  |  2020-02-06 15:30:53,553  INFO  [webscripts.connector.RemoteClient] [http-nio-8080-exec-5] Exception calling (POST) http://alfresco:8080/alfresco/s/api/upload?Alfresco-CSRFToken=Sive%2Btsjk9MgkcnvuzqxgWVbChWixOnLbTigdFZq7Tk%3D&alf_ticket=TICKET_3623dcfca1af1e0b4ca0009b7ad7ee018b77760c
share_1                  |  org.apache.http.client.ClientProtocolException
share_1                  | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
share_1                  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
share_1                  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
share_1                  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
share_1                  | 	at org.springframework.extensions.webscripts.connector.RemoteClient.service(RemoteClient.java:1167)
share_1                  | 	at org.springframework.extensions.webscripts.connector.RemoteClient.call(RemoteClient.java:804)
share_1                  | 	at org.springframework.extensions.webscripts.connector.HttpConnector.call(HttpConnector.java:143)
share_1                  | 	at org.springframework.extensions.webscripts.connector.AuthenticatingConnector.call(AuthenticatingConnector.java:293)
share_1                  | 	at org.springframework.extensions.webscripts.servlet.mvc.EndPointProxyController.handleRequestInternal(EndPointProxyController.java:328)
share_1                  | 	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
share_1                  | 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
share_1                  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
share_1                  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
share_1                  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
share_1                  | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
share_1                  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
share_1                  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
share_1                  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  | 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
share_1                  | 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)
share_1                  | 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
share_1                  | 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
share_1                  | 	at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:213)
share_1                  | 	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)
share_1                  | 	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
share_1                  | 	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
share_1                  | 	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  | 	at org.springframework.extensions.webscripts.servlet.SecurityHeadersFilter.doFilter(SecurityHeadersFilter.java:177)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  | 	at org.springframework.extensions.webscripts.servlet.CSRFFilter.doFilter(CSRFFilter.java:349)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  | 	at org.alfresco.web.site.servlet.SSOAuthenticationFilter.doFilter(SSOAuthenticationFilter.java:474)
share_1                  | 	at org.alfresco.web.site.servlet.SSOAuthenticationFilter.doFilter(SSOAuthenticationFilter.java:443)
share_1                  | 	at org.springframework.extensions.webscripts.servlet.BeanProxyFilter.doFilter(BeanProxyFilter.java:80)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  | 	at org.alfresco.web.site.servlet.MTAuthenticationFilter.doFilter(MTAuthenticationFilter.java:81)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
share_1                  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
share_1                  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
share_1                  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
share_1                  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
share_1                  | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
share_1                  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
share_1                  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
share_1                  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
share_1                  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
share_1                  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
share_1                  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
share_1                  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
share_1                  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
share_1                  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
share_1                  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
share_1                  | 	at java.base/java.lang.Thread.run(Thread.java:834)
share_1                  | Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
share_1                  | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:108)
share_1                  | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
share_1                  | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
share_1                  | 	... 64 more
share_1                  | Caused by: java.net.SocketException: Broken pipe (Write failed)
share_1                  | 	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
share_1                  | 	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
share_1                  | 	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
share_1                  | 	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124)
share_1                  | 	at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:136)
share_1                  | 	at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:167)
share_1                  | 	at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:113)
share_1                  | 	at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:144)
share_1                  | 	at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:121)
share_1                  | 	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
share_1                  | 	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:152)
share_1                  | 	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
share_1                  | 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
share_1                  | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
share_1                  | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
share_1                  | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
share_1                  | 	... 66 more
share_1                  | 2020-02-06 15:30:53,566  INFO  [webscripts.connector.RemoteClient] [http-nio-8080-exec-5] Error status 500 The stack details have been removed for security reasons.
share_1                  |  org.apache.http.client.ClientProtocolException
share_1                  | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
share_1                  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
share_1                  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
share_1                  | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
share_1                  | 	at org.springframework.extensions.webscripts.connector.RemoteClient.service(RemoteClient.java:1167)
share_1                  | 	at org.springframework.extensions.webscripts.connector.RemoteClient.call(RemoteClient.java:804)
share_1                  | 	at org.springframework.extensions.webscripts.connector.HttpConnector.call(HttpConnector.java:143)
share_1                  | 	at org.springframework.extensions.webscripts.connector.AuthenticatingConnector.call(AuthenticatingConnector.java:293)
share_1                  | 	at org.springframework.extensions.webscripts.servlet.mvc.EndPointProxyController.handleRequestInternal(EndPointProxyController.java:328)
share_1                  | 	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
share_1                  | 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
share_1                  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
share_1                  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
share_1                  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
share_1                  | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
share_1                  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
share_1                  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
share_1                  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  | 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
share_1                  | 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)
share_1                  | 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
share_1                  | 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
share_1                  | 	at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:213)
share_1                  | 	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)
share_1                  | 	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
share_1                  | 	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
share_1                  | 	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:389)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  | 	at org.springframework.extensions.webscripts.servlet.SecurityHeadersFilter.doFilter(SecurityHeadersFilter.java:177)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  | 	at org.springframework.extensions.webscripts.servlet.CSRFFilter.doFilter(CSRFFilter.java:349)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  | 	at org.alfresco.web.site.servlet.SSOAuthenticationFilter.doFilter(SSOAuthenticationFilter.java:474)
share_1                  | 	at org.alfresco.web.site.servlet.SSOAuthenticationFilter.doFilter(SSOAuthenticationFilter.java:443)
share_1                  | 	at org.springframework.extensions.webscripts.servlet.BeanProxyFilter.doFilter(BeanProxyFilter.java:80)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  | 	at org.alfresco.web.site.servlet.MTAuthenticationFilter.doFilter(MTAuthenticationFilter.java:81)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
share_1                  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
share_1                  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
share_1                  | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
share_1                  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
share_1                  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
share_1                  | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
share_1                  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
share_1                  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
share_1                  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
share_1                  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
share_1                  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
share_1                  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
share_1                  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
share_1                  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
share_1                  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
share_1                  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
share_1                  | 	at java.base/java.lang.Thread.run(Thread.java:834)
share_1                  | Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
share_1                  | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:108)
share_1                  | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
share_1                  | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
share_1                  | 	... 64 more
share_1                  | Caused by: java.net.SocketException: Broken pipe (Write failed)
share_1                  | 	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
share_1                  | 	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
share_1                  | 	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
share_1                  | 	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124)
share_1                  | 	at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:136)
share_1                  | 	at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:167)
share_1                  | 	at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:113)
share_1                  | 	at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:144)
share_1                  | 	at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:121)
share_1                  | 	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
share_1                  | 	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:152)
share_1                  | 	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
share_1                  | 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
share_1                  | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
share_1                  | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
share_1                  | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
share_1                  | 	... 66 more

```

**Comment by DeanTrivi** [comment]
I am having this issue after using ansible to install alfresco
